---
language: python
python: '3.6'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

# Spin off separate builds for each of the following versions
# of Ansible and Linux.
jobs:
  include:
    - env:
        - MOLECULE_SCENARIO=default
        - MOLECULEW_ANSIBLE=2.8.16
    - env:
        - MOLECULE_SCENARIO=default
        - MOLECULEW_ANSIBLE=2.8.16
    - env:
        - MOLECULE_SCENARIO=no-login
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=no-login
        - MOLECULEW_ANSIBLE=2.9.1

# Require Ubuntu 16.04
dist: xenial

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

branches:
  only:
    - master
    - /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
