---
language: python
python: '2.7'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

# Spin off separate builds for each of the following versions
# of Ansible and Linux.
matrix:
  include:
    - env:
        - MOLECULE_SCENARIO=default
        - MOLECULEW_ANSIBLE=2.5.10
    - env:
        - MOLECULE_SCENARIO=default
        - MOLECULEW_ANSIBLE=2.5.10
    - env:
        - MOLECULE_SCENARIO=no-login
        - MOLECULEW_ANSIBLE=2.8.2
    - env:
        - MOLECULE_SCENARIO=no-login
        - MOLECULEW_ANSIBLE=2.8.2

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

branches:
  only:
    - master
    - /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
