---
- name: install lightdm
  become: yes
  apt:
    name: lightdm
    state: present

- name: install libglib2.0-bin
  become: yes
  apt:
    name: libglib2.0-bin
    state: present

- name: enable auto-login
  become: yes
  template:
    src: lightdm.conf.j2
    dest: '{{ lightdm_conf_directory }}/{{ lightdm_overide_filename }}'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  register: lightdm_config

- name: apply glib schemas changes
  become: yes
  command: '/usr/bin/glib-compile-schemas {{ lightdm_glib_schemas_directory }}'
  when: lightdm_config.changed
