---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-lightdm
      lightdm_autologin_user: test_usr
      lightdm_autologin_user_timeout: 4242
      lightdm_greeter_allow_guest: yes
